export const ADD_NUMBER = 'ADD_NUMBER'
export const SUB_NUMBER = 'SUB_NUMBER'
export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'

export const CHANGE_BANNERS = 'CHANGE_BANNERS'
export const CHANGE_RECOMMENDS = 'CHANGE_RECOMMENDS'