// Generated by CoffeeScript 1.12.7
(function() {
  var list, list1, list3,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  list = [1, 2, 3, 4];

  list1 = [1, "xmg", true, [1, 2, 3]];

  console.log(list1, list);

  list3 = [1, 2, 3, 4, 5];

  console.log(list3[2]);

  console.log(indexOf.call(list3, 6) >= 0);

  console.log(list3.length);

  console.log(list3.slice(1, 3));

  console.log(list3.slice(1, 2));

}).call(this);

//# sourceMappingURL=06-数组.js.map
