// Generated by CoffeeScript 1.12.7
(function() {
  var arr, i, key, len, num, person, value;

  arr = [1, 2, 3, 4];

  for (i = 0, len = arr.length; i < len; i++) {
    num = arr[i];
    console.log(num + 1);
  }

  person = {
    name: 'YDH',
    age: 18,
    height: 1.7
  };

  for (key in person) {
    value = person[key];
    console.log(key, '=', value);
  }

}).call(this);

//# sourceMappingURL=12-循环语句.js.map
