// Generated by CoffeeScript 1.12.7
(function() {
  var a, b, name, num1, num2, num3, option, optionA, str, str1, str2, str3;

  option = true;

  optionA = false;

  option = true;

  optionA = false;

  a = null;

  console.log(a);

  b = void 0;

  console.log(b);

  num1 = 12;

  num2 = 21.1;

  num3 = -21;

  console.log(num1, num2, num3);

  str = 'HAHA';

  str1 = "hehe";

  console.log(str, str1);

  str2 = str + str1;

  console.log(str2);

  name = 'XMG';

  str3 = "hello, " + name;

  console.log(str3);

  console.log(str3.length);

  console.log(str3.toUpperCase());

  console.log(str3.toLowerCase());

  console.log("hello world".split(" ", '1'));

}).call(this);

//# sourceMappingURL=04-基本数据类型.js.map
