// Generated by CoffeeScript 1.12.7
(function() {
  var arr, range, range1, ref, rng;

  range = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

  range1 = [1, 2, 3, 4, 5, 6, 7, 8, 9];

  arr = [1, 2, 3, 4, 5, 6, 7, 8];

  rng = arr.slice(2, 3);

  [].splice.apply(arr, [2, 4].concat(ref = ["a", "b", "c", "d"])), ref;

  console.log(arr);

}).call(this);

//# sourceMappingURL=07-区间.js.map
