// Generated by CoffeeScript 1.12.7
(function() {
  var dog, person;

  person = {
    name: "YDH",
    age: 12,
    height: 1.7
  };

  console.log(person);

  dog = {
    name: "旺财",
    age: 2
  };

  console.log(dog);

  console.log(dog.name);

  console.log(dog.height);

  dog["food"] = "五花肉";

  console.log(dog);

  delete dog["name"];

  console.log(dog);

}).call(this);

//# sourceMappingURL=08-对象.js.map
