// Generated by CoffeeScript 1.12.7
(function() {
  var num, result, sum, sum1, sum2;

  sum = function(x) {
    return x * x;
  };

  num = function() {
    return 2 + 2;
  };

  console.log(sum(2));

  console.log(sum(3));

  console.log(num());

  sum1 = function(y, x) {
    if (x == null) {
      x = 2;
    }
    return x + y;
  };

  console.log(sum1(3));

  result = sum1(5);

  console.log(result);

  (function() {})();

  sum2 = function(x, y, c) {
    x + y + c;
    return 0;
  };

  console.log(sum2());

}).call(this);

//# sourceMappingURL=09-函数.js.map
