// Generated by CoffeeScript 1.12.7
(function() {
  var name;

  name = "YDH";

  console.log(4 === 4);

  console.log(4 !== 5);

  console.log(4 === 4 && 5 === 4);

  console.log(4 === 4 || 5 === 4);

}).call(this);

//# sourceMappingURL=10-语法糖.js.map
