// Generated by CoffeeScript 1.12.7
(function() {
  var age, scope;

  age = 16;

  if (age > 18) {
    console.log("成年人");
  } else {
    console.log("未成年人");
  }

  scope = 98;

  if (scope < 60) {
    console.log('不及格');
  } else if ((60 < scope && scope < 80)) {
    console.log("良好");
  } else if ((80 < scope && scope < 100)) {
    console.log("优秀");
  }

}).call(this);

//# sourceMappingURL=11-条件语句.js.map
